AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'Gemfile'
  TargetRubyVersion: 2.3

StringLiterals:
  EnforcedStyle: double_quotes
AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/BlockComments:
  Enabled: false
Rails/Date:
  Enabled: false
Style/Lambda:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
