CONSTANTS:

  ENABLE_FLAG:  "1"
  DISABLE_FLAG: "0"

  # Copyright
  COPYRIGHT: "Copyright &copy; All Rights Reserved."

  TIME_SEPARATE_TAG: ":"

  # 年度開始月
  START_FISCAL_YEAR: 4
  # 年度終了月
  END_FISCAL_YEAR: 3

  WEEKS:
    0: "日"
    1: "月"
    2: "火"
    3: "水"
    4: "木"
    5: "金"
    6: "土"

  # デフォルト新着記事掲載期間（単位: 月）
  DEFAULT_POSTED_PERIOD: 1

  # ロガープレフィックス
  LOGGER_PREFIX: "[RAILS]"

  REQUIRED_MARC: "*"

  # tmpディレクトリ
  TEMP_DIR: "<%= Rails.root.to_s + '/tmp/' %>"

  # 特別日程種別
  SPECIAL_DAY_TYPES:
    "001": "休暇"
    "002": "出勤"

  # 特別日程種別 休暇
  SPECIAL_DAY_HOLIDAY_TYPE:      "001"
  # 特別日程種別 出勤
  SPECIAL_DAY_BUSINESS_DAY_TYPE: "002"

  # 休暇種別状態
  LEAVE_TYPE_STATUSES:
    "001": "有効"
    "002": "無効"

  # 休暇種別状態 有効
  LEAVE_TYPE_ENABLE:  "001"
  # 休暇種別状態 無効
  LEAVE_TYPE_DISABLE: "002"

