default: &default
  menu:
    - title:  "admin_menu"
      header: true
      admin:  true
    - title:  "system_config"
      icon:   "fa-gear"
      path:   "/system_config/edit"
      admin:  true
    - title:  "user_config"
      icon:   "fa-user-plus"
      path:   "/#"
      admin:  true
    - title:  "reason"
      icon:   "fa-list-alt"
      path:   "/#"
      admin:  true
    - title:  "leave_type"
      icon:   "fa-copy"
      path:   "/#"
      admin:  true
    - title:  "article"
      icon:   "fa-newspaper-o"
      path:   "/articles"
      admin:  true
    - title:  "special_day"
      icon:   "fa-clipboard"
      path:   "/special_days"
      admin:  true
    - title:  "user_menu"
      header: true
    - title:  "attendance"
      icon:   "fa-calendar"
      path:   "/#"
    - title:  "user"
      icon:   "fa-user"
      path:   "/#"
    - title:  "leave_table"
      icon:   "fa-file-text"
      path:   "/#"
    - title:  "report"
      icon:   "fa-file"
      path:   "/#"

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
