default: &default
  menu:
    - title:  "admin_menu"
      header: true
      admin:  true
    - title:  "system_config"
      icon:   "fa-gear"
      path:   "/system_config/edit"
      admin:  true
    - title:  "user_config"
      icon:   "fa-user-plus"
      path:   "/user_configs"
      admin:  true
    - title:  "reason"
      icon:   "fa-list-alt"
      path:   "/reasons"
      admin:  true
    - title:  "leave_type"
      icon:   "fa-copy"
      path:   "/leave_types"
      admin:  true
    - title:  "article"
      icon:   "fa-newspaper-o"
      path:   "/articles"
      admin:  true
    - title:  "holiday"
      icon:   "fa-clipboard"
      path:   "/holidays"
      admin:  true
    - title:  "user_menu"
      header: true
    - title:  "attendance"
      icon:   "fa-calendar"
      path:   "/attendances"
    - title:  "user"
      icon:   "fa-user"
      path:   "/users"
    - title:  "leave_table"
      icon:   "fa-file-text"
      path:   "/leave_tables"
    - title:  "report"
      icon:   "fa-file"
      path:   "/reports"

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
